import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import { FC, PropsWithChildren } from 'react';

import type { Metadata } from 'next';

import '@/assets/styles/globals.css';
import '@/assets/styles/slider.css';
import StoreProvider from '@/store/components/StoreProvider';
import { theme } from '@/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <StoreProvider>
    <html lang="en">
      <body>
        <ConfigProvider theme={theme}>
          <AntdRegistry>{children}</AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  </StoreProvider>
);

export default RootLayout;
