import { Inter } from 'next/font/google';
import { FC, PropsWithChildren } from 'react';

import type { Metadata } from 'next';

import '@/assets/styles/globals.css';
import StoreProvider from '@/store/components/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <StoreProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  </StoreProvider>
);

export default RootLayout;
