import { FC, PropsWithChildren } from 'react';

import Providers from './providers';

import type { Metadata } from 'next';

import '@/assets/styles/globals.scss';

import StoreProvider from '@/store/components/StoreProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <StoreProvider>
    <html lang="ru">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  </StoreProvider>
);

export default RootLayout;
