import { color, breakpoint } from './variables';

export const theme = {
  token: {
    colorWarning: color.warning,
    colorError: color.error.default,
    colorSuccess: color.success,
    colorPrimary: color.accent.default,
    colorInfo: color.primary.default,
    colorTextBase: color.text.primary,

    screenXSMin: 1,
    screenXS: 1,
    screenXSMax: breakpoint.xs,
    screenSMMin: breakpoint.xs + 1,
    screenSM: breakpoint.xs + 1,
    screenSMMax: breakpoint.sm,
    screenMDMin: breakpoint.sm + 1,
    screenMD: breakpoint.sm + 1,
    screenMDMax: breakpoint.md,
    screenLGMin: breakpoint.md + 1,
    screenLG: breakpoint.md + 1,
    screenLGMax: breakpoint.lg,
    screenXLMin: breakpoint.lg + 1,
    screenXL: breakpoint.lg + 1,
    screenXLMax: breakpoint.xl,

    fontFamily: 'Gilroy',
  },

  components: {
    Button: {
      fontSize: 16,
      fontSizeSM: 14,
      contentFontSizeSM: 14,
      paddingInlineLG: 24,
      paddingInlineSM: 17,

      controlHeight: 48,
      controlHeightLG: 48,
      controlHeightSM: 40,

      borderRadius: 64,
      borderRadiusLG: 64,
      borderRadiusSM: 64,
      dangerShadow: 'unset',
      defaultShadow: 'unset',
      primaryShadow: 'unset',
      borderColorDisabled: 'none',
      defaultBorderColor: color.accent.default,
      colorPrimaryBorder: color.accent.default,
      defaultBg: color.transparent,
      defaultHoverBg: color.transparent,
      defaultActiveBg: color.transparent,
      ghostBg: color.white,
      defaultColor: color.accent.default,
      colorLink: color.text.primary,
      colorLinkHover: color.link.hover,
      colorLinkActive: color.link.active,
    },
    Breadcrumb: {
      itemColor: color.text.tertiary,
      linkColor: color.text.tertiary,
      colorText: color.text.primary,
      lastItemColor: color.text.primary,
      colorBgTextHover: color.text.quinary,
      lineWidthFocus: 1,
      fontSize: 16,
      fontSizeSM: 14,
      fontHeight: 24,
      fontHeightSM: 22,
    },
    Carousel: {
      colorBgContainer: color.accent.default,
      arrowOffset: 24,
      dotOffset: -16,
    },
    Divider: {
      colorSplit: color.text.quinary,
    },
    Pagination: {
      colorPrimary: color.accent.default,
      colorText: color.text.primary,
      colorPrimaryHover: color.accent.hover,
      colorTextDisabled: color.text.quaternary,
      borderRadius: 50,
      controlHeight: 40,
      fontSize: 16,
      fontHeight: 40,
      itemSize: 40,
    },
    Dropdown: {
      fontSize: 16,
      paddingBlock: 6,
    },
    Cascader: {
      optionSelectedBg: color.primary.bg,
      dropdownHeight: 'clamp(100px, 600px, 75vh)',
      menuPadding: 4,
      optionPadding: 12,
      controlItemWidth: 308,
      colorSplit: color.border.secondary,
      fontSize: 16,
      lineHeight: 1.5,
      lineWidth: 4,
      fontSizeIcon: 16,
      optionSelectedFontWeight: 400,
    },
    Menu: {
      activeBarBorderWidth: 0,
      fontSize: 16,
    },
    Badge: {
      fontSize: 16,
      textFontSize: 16,
      textFontWeight: 500,
      fontSizeSM: 10,
      textFontSizeSM: 10,
      indicatorHeightSM: 16,
    },
    Segmented: {
      itemColor: color.text.primary,
      itemHoverBg: color.fill.default,
      itemHoverColor: color.text.primary,
      itemSelectedBg: color.primary.default,
      itemSelectedColor: color.white,
      trackBg: color.transparent,
      controlHeight: 48,
      controlPaddingHorizontal: 16,
      fontSize: 16,
      borderRadius: 64,
      boxShadowTertiary: 'none',
    },
    Collapse: {
      contentBg: color.white,
      headerBg: color.white,
      colorBorder: color.border.secondary,
      borderRadiusLG: 16,
      headerPadding: 24,
      headerPaddingXS: 16,
      contentPadding: '0 24px 24px',
      fontSizeIcon: 30,
    },
    Modal: {
      titleFontSize: 30,
      fontWeightStrong: 500,
      boxShadow: '0px 4px 20px 0px rgba(64, 54, 49, 0.09)',
      fontFamily: 'Gilroy',
      fontHeight: 32,
    },
    Checkbox: {
      controlInteractiveSize: 24,
    },
    Input: {
      paddingInline: 12,
      paddingBlock: 7,
    },
    Form: {
      itemMarginBottom: 16,
    },
    Tabs: {
      inkBarColor: color.primary.default,
      itemHoverColor: color.primary.hover,
      itemSelectedColor: color.primary.default,
      itemActiveColor: color.primary.active,
      colorIcon: color.primary.default,
    },
  },
};
