import { breakpoint, color } from './assets/styles/variables';

export const theme = {
  token: {
    colorWarning: color.warning,
    colorError: color.error.default,
    colorSuccess: color.success,
    colorPrimary: color.accent.default,
    colorInfo: color.primary.default,
    colorTextBase: color.text.primary,

    screenXSMin: 1,
    screenXS: breakpoint.xs,
    screenXSMax: breakpoint.xs,
    screenSMMin: breakpoint.xs + 1,
    screenSM: breakpoint.sm,
    screenSMMax: breakpoint.sm,
    screenMDMin: breakpoint.sm + 1,
    screenMD: breakpoint.md,
    screenMDMax: breakpoint.md,
    screenLGMin: breakpoint.md + 1,
    screenLG: breakpoint.lg,
    screenLGMax: breakpoint.lg,
  },

  components: {
    Button: {
      fontSize: 16,
      fontSizeSM: 14,
      contentFontSizeSM: 14,
      paddingInlineLG: 24,
      paddingInlineSM: 17,

      controlHeight: 48,
      controlHeightLG: 48,
      controlHeightSM: 40,

      borderRadius: 64,
      borderRadiusLG: 64,
      borderRadiusSM: 64,
      dangerShadow: 'unset',
      defaultShadow: 'unset',
      primaryShadow: 'unset',
      borderColorDisabled: 'none',
      defaultBorderColor: color.accent.default,
      colorPrimaryBorder: color.accent.default,
      defaultBg: color.transparent,
      defaultHoverBg: color.transparent,
      defaultActiveBg: color.transparent,
      ghostBg: color.white,
      defaultColor: color.accent.default,
      colorLink: color.text.primary,
      colorLinkHover: color.link.hover,
      colorLinkActive: color.link.active,
    },
    Breadcrumb: {
      itemColor: color.text.tertiary,
      linkColor: color.text.tertiary,
      colorText: color.text.primary,
      lastItemColor: color.text.primary,
      colorBgTextHover: color.text.quinary,
      lineWidthFocus: 1,
      fontSize: 16,
      fontSizeSM: 14,
      fontHeight: 24,
      fontHeightSM: 22,
    },
    Carousel: {
      colorBgContainer: color.accent.default,
      arrowOffset: 24,
      dotOffset: -16,
    },
    Divider: {
      colorSplit: color.text.quinary,
    },
    Pagination: {
      colorPrimary: color.accent.default,
      colorText: color.text.primary,
      colorPrimaryHover: color.accent.hover,
      colorTextDisabled: color.text.quaternary,
      borderRadius: 50,
      controlHeight: 40,
      controlHeightSM: 32,
      fontSize: 16,
      fontSizeSM: 14,
      fontHeight: 24,
      fontHeightSM: 22,
      itemSize: 40,
      itemSizeSM: 32,
    },
    Dropdown: {
      paddingBlock: 10,
      fontFamily: 'Gilroy',
    },
  },
};
