import { color } from './assets/styles/color';

export const theme = {
  token: {
    colorWarning: color.warning,
    colorError: color.error.default,
    colorSuccess: color.success,
    colorPrimary: color.accent.default,
    colorInfo: color.primary.default,
    colorTextBase: color.text.primary,
    screenLG: 1024,
    screenSM: 767,
  },

  components: {
    Button: {
      fontSize: 16,
      fontSizeSM: 14,
      contentFontSizeSM: 14,
      paddingInlineLG: 24,
      paddingInlineSM: 17,

      controlHeight: 48,
      controlHeightLG: 48,
      controlHeightSM: 40,

      borderRadius: 64,
      borderRadiusLG: 64,
      borderRadiusSM: 64,
      dangerShadow: 'unset',
      defaultShadow: 'unset',
      primaryShadow: 'unset',
      borderColorDisabled: 'none',
      defaultBorderColor: color.accent.default,
      colorPrimaryBorder: color.accent.default,
      defaultBg: color.transparent,
      defaultHoverBg: color.transparent,
      defaultActiveBg: color.transparent,
      ghostBg: color.white,
      defaultColor: color.accent.default,
      colorLink: color.text.primary,
      colorLinkHover: color.link.hover,
      colorLinkActive: color.link.active,
    },
    Breadcrumb: {
      itemColor: color.text.tertiary,
      linkColor: color.text.tertiary,
      colorText: color.text.primary,
      lastItemColor: color.text.primary,
      colorBgTextHover: color.text.quinary,
      borderRadiusSM: 64,
      lineWidthFocus: 1,
      marginXXS: 0,
      paddingXXS: 3,
      fontSize: 16,
      fontHeight: 24,
    },
    Carousel: {
      colorBgContainer: color.accent.default,
      arrowOffset: 24,
      dotOffset: -16,
    },
    Divider: {
      colorSplit: color.text.quinary,
    },
    Pagination: {
      colorPrimary: color.accent.default,
      borderRadius: 50,
      controlHeight: 40,
      colorText: color.text.primary,
      colorPrimaryHover: color.accent.hover,
      colorTextDisabled: color.text.quaternary,
      controlHeightSM: 32,
    },
    Dropdown: {
      paddingBlock: 10,
      fontFamily: 'Gilroy',
    },
  },
};
